#!/bin/sh

### BEGIN INIT INFO
# Provides:		tedmon
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Starts tedmon
# Description:		tedmon collects data from ted5000 devices
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
APP=/opt/mtools/bin/tedmon.py
PIDFILE=/var/run/tedmon.pid
LOGFILE=/var/log/tedmon.log

set -e

case "$1" in
    start)
    echo -n "Starting tedmon:"
    $APP --ip --ip-host 192.168.3.61 --rrd --quiet >> $LOGFILE 2>&1 &
    pid=$!
    echo $pid > $PIDFILE
    echo
    ;;

    stop)
    echo -n "Shutting down tedmon:"
    if [ -f $PIDFILE ]; then
        kill `cat $PIDFILE`
        rm $PIDFILE
    fi
    echo
    ;;
    
    *)
    echo "Usage: $0 {start|stop}" >&2
    exit 1
    ;;
esac

exit 0
